---
# Role handlers

- name: Apache_vhosts run post script
  shell: "{{ apache_vhosts_post_script }}"
  args:
    warn: no
  become: >-
    {{ apache_vhosts_vhost.post_script_becomer
       | default(apache_vhosts_vhost_defaults.post_script_become) }}
  become_user: >-
    {{ apache_vhosts_vhost.post_script_become_user
       | default(apache_vhosts_vhost_defaults.post_script_become_user) }}
  become_method: >-
    {{ apache_vhosts_vhost.post_script_become_method
       | default(apache_vhosts_vhost_defaults.post_script_become_method)
       | default("sudo") }}
  loop: "{{ apache_vhosts_to_manage }}"
  loop_control:
    loop_var: apache_vhosts_vhost
    label: "{{ apache_vhosts_post_script }}"
  when: apache_vhosts_post_script | length > 0
  listen: run post script
  vars:
    apache_vhosts_post_script: >-
      {{ apache_vhosts_vhost.post_script
         | default(apache_vhosts_vhost_defaults.post_script)
         | default("") }}
