---
# Role handlers

- name: Apache_vhosts reload httpd
  ansible.builtin.service:
    name: httpd
    state: reloaded
  when: >-
    apache_vhosts_to_manage
    | selectattr("reload_httpd", "defined")
    | selectattr("reload_httpd", "equalto", true)
    | length > 0
    or (apache_vhosts_to_manage
        | selectattr("reload_httpd", "undefined")
        | length > 0
        and apache_vhosts_defaults.reload_httpd | default(false))
  listen:
    - apache vhosts reload
    - httpd vhosts reload

- name: Apache_vhosts run post script
  ansible.builtin.command: "{{ apache_vhosts_post_script }}"
  args:
    warn: no
  become: >-
    {{ apache_vhosts_vhost.post_script_become
       | default(apache_vhosts_defaults.post_script_become)
       | bool }}
  become_user: >-
    {{ apache_vhosts_vhost.post_script_become_user
       | default(apache_vhosts_defaults.post_script_become_user) }}
  become_method: >-
    {{ apache_vhosts_vhost.post_script_become_method
       | default(apache_vhosts_defaults.post_script_become_method)
       | default("sudo") }}
  loop: "{{ apache_vhosts_to_manage }}"
  loop_control:
    loop_var: apache_vhosts_vhost
    label: "{{ apache_vhosts_post_script }}"
  when:
    - apache_vhosts_post_script | length > 0
    - >-
      apache_vhosts_vhost.post_script_expect_responses
      | default(apache_vhosts_defaults.post_script_expect_responses)
      is undefined
  listen: run post script
  no_log: "{{ apache_vhosts_no_log | bool }}"
  vars:
    apache_vhosts_post_script: >-
      {{ apache_vhosts_vhost.post_script
         | default(apache_vhosts_defaults.post_script)
         | default("") }}

- name: Apache_vhosts run post script with expect
  ansible.builtin.expect:
    command: "{{ apache_vhosts_post_script }}"
    chdir: "{{ apache_vhosts_post_script_chdir }}"
    responses: >-
      {{ apache_vhosts_vhost.post_script_expect_responses
         | default(apache_vhosts_defaults.post_script_expect_responses) }}
    timeout: >-
      {{ apache_vhosts_vhost.post_script_expect_timeout
         | default(apache_vhosts_defaults.post_script_expect_timeout)
         | default(60) }}
  loop: "{{ apache_vhosts_to_manage }}"
  loop_control:
    loop_var: apache_vhosts_vhost
    label: "{{ apache_vhosts_post_script }}"
  when:
    - apache_vhosts_post_script | length > 0
    - >-
      apache_vhosts_vhost.post_script_expect_responses
      | default(apache_vhosts_defaults.post_script_expect_responses)
      is defined
  listen: run post script
  no_log: "{{ apache_vhosts_no_log | bool }}"
  vars:
    apache_vhosts_post_script: >-
      {{ apache_vhosts_vhost.post_script
         | default(apache_vhosts_defaults.post_script)
         | default("") }}
    apache_vhosts_post_script_chdir: >-
      {{ apache_vhosts_vhost.post_script_chdir
         | default(apache_vhosts_defaults.post_script_chdir)
         | default(omit) }}
    ansible_become: >-
      {{ apache_vhosts_vhost.post_script_become
         | default(apache_vhosts_defaults.post_script_become) }}
    ansible_become_user: >-
      {{ apache_vhosts_vhost.post_script_become_user
         | default(apache_vhosts_defaults.post_script_become_user) }}
    ansible_become_method: >-
      {{ apache_vhosts_vhost.post_script_become_method
         | default(apache_vhosts_defaults.post_script_become_method)
         | default("sudo") }}
