---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check virtual hosts config files
      stat:
        path: "{{ item }}"
      loop:
        - /etc/httpd/conf.ansible.d/myhost.conf
        - /etc/httpd/conf.ansible.d/myhost_ssl.conf
      register: check_config_files_result

    - name: Verify that virtual hosts config files exist
      assert:
        that: >-
          {{ check_config_files_result.results
             | selectattr("stat.exists", "equalto", false)
             | list
             | length == 0 }}
